pthread_create:pthread_create.c
	gcc  pthread_create.c -lpthread -o pthread_create 

pthread_create2:pthread_create2.c
	gcc  pthread_create2.c -lpthread -o pthread_create2
 
pthread_create3:pthread_create3.c
	gcc  pthread_create3.c -lpthread -o pthread_create3 
.PHONE:clean
clean:
	rm  pthread_create 
