pthread_create:pthread_create.c #make 默认是第一个目标。 
	gcc  pthread_create.c -lpthread -o pthread_create 

pthread_create2:pthread_create2.c
	gcc  pthread_create2.c -lpthread -o pthread_create2
 
pthread_create3:pthread_create3.c
	gcc  pthread_create3.c -lpthread -o pthread_create3 

pthread_create4:pthread_create4.c
	gcc  pthread_create4.c -lpthread -o pthread_create4
pthread_create5:pthread_create5.c
	gcc  pthread_create5.c -lpthread -o pthread_create5
pthread_create6:pthread_create6.c
	gcc  pthread_create6.c -lpthread -o pthread_create6
.PHONE:clean
clean:
	rm  pthread_create pthread_create2 pthread_create3  pthread_create4\
pthread_create5 pthread_create6
